In [ ]:
#Notes

# mvFile Name from dataRecord is structured into 60 x 5 numpy array
# Every file name is of the same type: There does not seem to be a pattern to the numbers
#Most of them are between 1 and 5



#Every hc movie is repeated 5 times
#Every hc_pred movie is repeated 20 times
#Every hc_reg movie is repeated 20 times

In [3]:
import scipy as sc
from scipy import io
import numpy as np

#dat = sc.io.loadmat('H6214.010.mat')
data = sc.io.loadmat('H6214.010_3_Ch48.mat')

range(0, 4)

In [125]:
temp = []
folder = 'dataRecord'
subfolder = 'spkTimes'
variable = data[folder][subfolder]

for a in range(60):
    for b in range(5):
        temp.append(variable[a][b])
        
len(temp)

300

In [61]:
data['dataRecord'].dtype.names


('iSweep',
 'conIndex',
 'muaRawSignal',
 'durSecActual',
 'elapsedSecs',
 'mvFileName',
 'spkTimes',
 'movieFrameTimesDetected',
 'epRawSignal')

In [117]:
data['dataRecord']['spkTimes'][]

array([ array([[ 6801,  6826,  6844,  7917,  7952, 11027, 19292, 25601, 28190,
        29624, 31708, 38327, 38365, 40980, 43106, 44243, 44779, 44819,
        51582, 51623, 53301, 53394]], dtype=uint16),
       array([[ 5136, 10578, 13434, 17880, 18638, 25709, 27565, 40120, 50697,
        52198]], dtype=uint16),
       array([[ 5895,  6554,  8691,  8733, 10988, 11016, 15117, 22595, 26584,
        32478, 39503, 43586, 51455]], dtype=uint16),
       array([[ 6694,  9825, 15735, 15786, 15819, 17456, 19890, 23732, 24377,
        26459, 30562, 36391, 39487, 41737, 43705, 47018, 48685]], dtype=uint16),
       array([[11178, 13091, 13154, 13338, 17684, 23594, 23628, 24722, 26266,
        27597, 31580, 33553, 35912, 35953, 38189, 38206, 39561, 40460,
        42079, 44670, 46177, 49319, 51305, 51318]], dtype=uint16)], dtype=object)

In [85]:
len(data['dataRecord']['mvFileName'][data['dataRecord']['mvFileName'] == 'McGill_clips_hc_pred_0000_02'])

20